Added workflows
SE750-DART/nerds-oppose-society pull request #15
Opened 2021-04-27 05:36 UTC by Alxjlv

Closes #14 

Both frontend and backend CI yml files added to run tests and linting

2021-04-27 12:10 UTC, taitfuller commented on .github/workflows/backend.yml
> +            npm test
```suggestion
            npm test
```
```suggestion
            npm test
            
```

2021-04-27 12:11 UTC, taitfuller requested changes
Overall looks good! Prettier is setup for the repository root as of #18 but if you could run `prettier --write .` on these that'd be great!

2021-04-27 12:27 UTC, Alxjlv commented
> Overall looks good! Prettier is setup for the repository root as of #18 but if you could run `prettier --write .` on these that'd be great!

@taitfuller I'm not entirely sure what you mean by running `prettier --write .` - wouldn't that go against the purpose of the action? None of the write changes would be saved to the repo, and if changes are required, then that should be a fail state.

Is there a prettier command I can use to see if `--write` was somehow missed?

2021-04-27 12:32 UTC, taitfuller commented
Ah sorry! I meant to run prettier on the code that you're submitting so that the `.yml` files are formatted consistently by Prettier. All future commits after #18 will have this occur automatically with the precommit hook 👌🏼

2021-04-28 05:29 UTC, taitfuller approved these changes
Looks great!

2021-04-28 05:30 UTC, merged